[common]
build_flags       = -Wa,-g
build_unflags     =
platform          = atmelavr
upload_protocol   = arduino_as_isp
upload_flags      =
  -e
  -u

[env:AT90S1200]
extends           = common
board_build.mcu   = at90s1200
