name: Run DRC checks

on:
  push:
    paths:
      - '**/*.kicad_pcb'

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      projects: ${{ steps.projects.outputs.projects }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: List Projects
        id: projects
        run: |
          projects_json="[]"
          for dir in */; do
            dir=${dir%/}
            if [ -d "$dir" ]; then
              pcb_file=$(ls "$dir"/*.kicad_pcb 2>/dev/null | head -n 1)
              if [ -n "$pcb_file" ]; then
                pcb_file=${pcb_file#$dir/}
                projects_json=$(jq -c \
                  --arg name "$dir" \
                  --arg pcb "$pcb_file" \
                  '. += [{name: $name, pcb: $pcb}]' \
                  <<< "$projects_json")
              fi
            fi
          done
          echo "projects=$projects_json" >> "$GITHUB_OUTPUT"

  kicad_drc:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:10.0-full
      options: --user root
    needs: define-matrix
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    name: DRC
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup libraries
        run: |
          mkdir -p $HOME/.config
          cp -r /home/kicad/.config/kica* $HOME/.config/

      - name: Run KiCad DRC
        id: drc
        working-directory: ${{ matrix.project.name }}
        run: kicad-cli pcb drc --output drc.rpt --exit-code-violations ${{ matrix.project.pcb }}

      - name: Upload report
        if: ${{ failure() }}
        run: |
          echo "<details><summary>DRC</summary>" >> $GITHUB_STEP_SUMMARY
          echo "<pre><code>" >> $GITHUB_STEP_SUMMARY
          cat ${{ matrix.project.name }}/drc.rpt >> $GITHUB_STEP_SUMMARY
          echo "</code></pre>" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
