name: Run ERC and DRC checks

on: [push]

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      projects: ${{ steps.projects.outputs.projects }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: List Projects
        id: projects
        run: |
          projects=()
          for dir in */; do
            dir=${dir%/}
            if [ -d "$dir" ]; then
              sch_files=("$dir"/*.kicad_sch)
              pcb_files=("$dir"/*.kicad_pcb)
              if [ -e "${sch_files[0]}" ] && [ -e "${pcb_files[0]}" ]; then
                projects+=("$dir")
              fi
            fi
          done
          json_output=$(printf '%s\n' "${projects[@]}" | jq -R . | jq -s -c .)
          echo "projects=$json_output" >> "$GITHUB_OUTPUT"
  kicad_job:
    runs-on: ubuntu-latest
    needs: define-matrix
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    name: ERC+DRC
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run KiCad ERC
        id: erc
        uses: sparkengineering/kicad-action@v4
        with:
          kicad_sch: ${{ matrix.project }}/${{ matrix.project }}.kicad_sch
          sch_erc: true

      - name: Run KiCad DRC
        id: drc
        uses: sparkengineering/kicad-action@v4
        with:
          kicad_pcb: ${{ matrix.project }}/${{ matrix.project }}.kicad_pcb
          pcb_drc: true

      - name: Upload report
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: ${{ matrix.project }}-erc.rpt
          path: ${{ github.workspace }}/${{ matrix.project }}/*.rpt
