name: Run ERC and DRC checks

on: [push]

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      projects: ${{ steps.projects.outputs.projects }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: List Projects
        id: projects
        run: |
          projects_json="[]"
          for dir in */; do
            dir=${dir%/}
            if [ -d "$dir" ]; then
              sch_file=$(ls "$dir"/*.kicad_sch 2>/dev/null | head -n 1)
              pcb_file=$(ls "$dir"/*.kicad_pcb 2>/dev/null | head -n 1)
              if [ -n "$sch_file" ] && [ -n "$pcb_file" ]; then
                sch_file=${sch_file#$dir/}
                pcb_file=${pcb_file#$dir/}
                projects_json=$(jq -c \
                  --arg name "$dir" \
                  --arg sch "$sch_file" \
                  --arg pcb "$pcb_file" \
                  '. += [{name: $name, sch: $sch, pcb: $pcb}]' \
                  <<< "$projects_json")
              fi
            fi
          done
          echo "projects=$projects_json" >> "$GITHUB_OUTPUT"
  kicad_job:
    runs-on: ubuntu-latest
    needs: define-matrix
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    name: ERC+DRC
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run KiCad ERC
        id: erc
        uses: sparkengineering/kicad-action@v4
        with:
          kicad_sch: ${{ matrix.project.name }}/${{ matrix.project.sch }}
          sch_erc: true

      - name: Run KiCad DRC
        id: drc
        if: always()
        uses: sparkengineering/kicad-action@v4
        with:
          kicad_pcb: ${{ matrix.project.name }}/${{ matrix.project.pcb }}
          pcb_drc: true

      - name: Upload report
        if: ${{ failure() }}
        run: |
          echo "<details><summary>ERC</summary>```" >> $GITHUB_STEP_SUMMARY
          cat ${{ github.workspace }}/${{ matrix.project.name }}/erc.rpt >> $GITHUB_STEP_SUMMARY
          echo "```</details><details><summary>DRC</summary>```"  >> $GITHUB_STEP_SUMMARY
          cat ${{ github.workspace }}/${{ matrix.project.name }}/drc.rpt >> $GITHUB_STEP_SUMMARY
          echo "```</details>"  >> $GITHUB_STEP_SUMMARY

